name: actividad_1_ingesta_de_datos_api

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      
      - name: paso1 - Crea entorno virtual
        run: python -m venv venv

      - name: paso2 - Activar entorno virtual
        run: ./venv/Scripts/activate

      - name: paso3 - Actualizar pip
        run: pip install --upgrade pip

      - name: paso4 - Instalar dependencias
        run: pip install -e .

      - name: paso5 - Ejecutar script de ingesta
        run: python src/bigdata/ingesta.py

      - name: paso6 - Guardar artefactos generados antes de la limpieza
        uses: actions/upload-artifact@v4
        with:
          name: archivos_ingesta
          path: |
            src/bigdata/static/db/ingesta.sqlite3
            src/bigdata/static/xlsx/export_books.xlsx
            src/bigdata/static/xlsx/export_books.csv
            src/bigdata/static/auditoria/auditoria.txt
          retention-days: 7

      - name: paso7 - Ejecutar limpieza de datos
        run: python src/bigdata/limpieza.py
      
      - name: paso8 - Guardar artefactos generados posterior a la limpieza
        uses: actions/upload-artifact@v4
        with:
          name: archivos_limpiados
          path: |
            src/bigdata/static/limpieza/authors.csv
            src/bigdata/static/limpieza/books_authors.csv
            src/bigdata/static/limpieza/books_categories.csv
            src/bigdata/static/limpieza/books.csv
            src/bigdata/static/limpieza/categories.csv
            src/bigdata/static/auditoria/auditoria_limpieza.txt
          retention-days: 7  

      - name: Configurar credenciales de Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: paso9 - Ejecutar y crear transformaciones
        run: python src/bigdata/transformacion.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generación de informe de transformaciones"
          commit_user_name: "Lauraarboledag [GitHub Actions]"
          commit_user_email: "laura.arboledag@est.iudigital.edu.co"
          commit_author: "Laura Arboleda <laura.arboledag@est.iudigital.edu.co>"
